FROM ubuntu:20.04 as builder

RUN apt-get update -y && \
    apt-get -y upgrade 
RUN apt-get install -y curl
COPY bqq /bqq
RUN curl -sL https://deb.nodesource.com/setup_15.x -o setup_14.sh && \
    sh ./setup_14.sh && \
    apt update -y && \
    apt install nodejs
WORKDIR /bqq
RUN npm install -g @angular/cli
RUN npm install --global yarn && \
    yarn install && \
    ng build
FROM nginx:latest
COPY --from=builder /bqq/dist/TanitLab /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf




